import Dexie, { type Table } from 'dexie';

export function nowMs(): number {
  return Date.now();
}

export type BaseEntity = {
  id: string;
  videoId: string;
  createdAt: number;
  updatedAt: number;
  schemaVersion: number;
};

export type TranscriptRow = BaseEntity & {
  language: string;
  isAutoGenerated: boolean;
  metadata: { totalDuration: number; chunkCount: number; fetchedAt: number };
  chunks: Array<{
    id: string;
    text: string;
    startTime: number;
    endTime: number;
    duration: number;
    index: number;
  }>;
};

export type SemanticChunkRow = BaseEntity & {
  semanticChunkId: string;
  text: string;
  startTime: number;
  endTime: number;
  transcriptChunkIds: string[];
};

export type EmbeddingRow = BaseEntity & {
  semanticChunkId: string;
  model: string;
  vector: number[];
};

export type NoteRow = BaseEntity & {
  type: 'concise' | 'detailed' | 'interview' | 'revision' | 'custom';
  title: string;
  content: string;
  format: 'markdown' | 'plain';
  tags: string[];
  isPinned: boolean;
  timestampAnchors?: Array<{ startTime: number; endTime?: number; label?: string }>;
};

export type ChapterRow = BaseEntity & {
  title: string;
  chapters: Array<{
    id: string;
    title: string;
    startTime: number;
    endTime: number;
    summary: string;
    keyPoints: string[];
  }>;
};

export type FlashcardRow = BaseEntity & {
  flashcardId: string;
  front: string;
  back: string;
  difficulty: 'easy' | 'medium' | 'hard';
  nextReviewDate: number;
  intervalDays: number;
  repetitions: number;
  easeFactor: number;
  lastReviewedAt?: number;
};

export type QuizRow = BaseEntity & {
  quizId: string;
  mode: 'beginner' | 'interview' | 'revision';
  title: string;
  questions: Array<{
    id: string;
    question: string;
    options: string[];
    correctAnswerIndex: number;
    explanation: string;
    difficulty: 'easy' | 'medium' | 'hard';
    timestamp?: number;
  }>;
};

export type AnalyticsRow = BaseEntity & {
  kind: 'learning_event' | 'confusion' | 'ai_generation';
  payload: Record<string, unknown>;
};

export class StudyflowDB extends Dexie {
  transcripts!: Table<TranscriptRow, string>;
  semanticChunks!: Table<SemanticChunkRow, string>;
  embeddings!: Table<EmbeddingRow, string>;
  notes!: Table<NoteRow, string>;
  chapters!: Table<ChapterRow, string>;
  flashcards!: Table<FlashcardRow, string>;
  quizzes!: Table<QuizRow, string>;
  analytics!: Table<AnalyticsRow, string>;

  constructor() {
    super('yt-studyflow');

    this.version(1).stores({
      transcripts: 'id, videoId, updatedAt',
      semanticChunks: 'id, videoId, startTime, endTime, updatedAt',
      embeddings: 'id, videoId, semanticChunkId, model, updatedAt',
      notes: 'id, videoId, type, createdAt, updatedAt, isPinned',
      chapters: 'id, videoId, updatedAt',
      flashcards: 'id, videoId, nextReviewDate, difficulty',
      quizzes: 'id, videoId, mode, updatedAt',
      analytics: 'id, videoId, kind, createdAt',
    });
  }
}

let dbInstance: StudyflowDB | null = null;

export function getDb(): StudyflowDB {
  if (!dbInstance) dbInstance = new StudyflowDB();
  return dbInstance;
}

export async function ensureDbReady(): Promise<void> {
  await getDb().open();
}

export const DbIds = {
  transcript: (videoId: string) => `transcript|${videoId}`,
  semanticChunk: (videoId: string, chunkId: string) => `chunk|${videoId}|${chunkId}`,
  embedding: (videoId: string, chunkId: string, model: string) =>
    `embed|${videoId}|${chunkId}|${model}`,
  note: (videoId: string, noteId: string) => `note|${videoId}|${noteId}`,
  chapters: (videoId: string) => `chapters|${videoId}`,
  flashcard: (videoId: string, cardId: string) => `fc|${videoId}|${cardId}`,
  quiz: (videoId: string, quizId: string) => `quiz|${videoId}|${quizId}`,
  analytics: (videoId: string, id: string) => `analytics|${videoId}|${id}`,
};
