import Dexie, { type Table } from 'dexie';

export function nowMs(): number {
  return Date.now();
}

export type BaseEntity = {
  id: string;
  videoId: string;
  createdAt: number;
  updatedAt: number;
  schemaVersion: number;
};

export type TranscriptRow = BaseEntity & {
  language: string;
  isAutoGenerated: boolean;
  metadata: { totalDuration: number; chunkCount: number; fetchedAt: number };
  chunks: Array<{
    id: string;
    text: string;
    startTime: number;
    endTime: number;
    duration: number;
    index: number;
  }>;
};

export type SemanticChunkRow = BaseEntity & {
  semanticChunkId: string;
  playlistId?: string;
  videoTitle?: string;
  text: string;
  startTime: number;
  endTime: number;
  transcriptChunkIds: string[];
};

export type EmbeddingRow = BaseEntity & {
  semanticChunkId: string;
  model: string;
  vector: number[];
};

export type PlaylistRow = {
  id: string;
  title: string;
  videoIds: string[];
  videoTitles: Record<string, string>;
  createdAt: number;
  updatedAt: number;
  schemaVersion: number;
};

export type StudyPlanRow = {
  id: string;
  playlistId: string;
  topic: string;
  level: 'beginner' | 'intermediate' | 'advanced';
  estimatedMinutes: number;
  prerequisites: string[];
  segments: Array<{
    id: string;
    title: string;
    description: string;
    startTime: number;
    endTime: number;
    videoId: string;
    videoTitle?: string;
    watched?: boolean;
  }>;
  keyConcepts: string[];
  interviewQuestions: string[];
  conceptMap: Array<{
    id: string;
    label: string;
    children?: Array<{ id: string; label: string; children?: unknown[] }>;
  }>;
  retrievalEvidence: Array<{
    chunkId: string;
    videoId: string;
    videoTitle?: string;
    startTime: number;
    endTime: number;
    excerpt: string;
    score: number;
  }>;
  nextTopics: string[];
  notesPreview: string;
  quickQuiz: Array<{
    id: string;
    question: string;
    options: string[];
    correctAnswer: number;
    explanation: string;
  }>;
  mastery: {
    percent: number;
    quizCorrect: number;
    quizTotal: number;
    flashcardsReviewed: number;
    flashcardsTotal: number;
    segmentsWatched: number;
    segmentsTotal: number;
    revisionSessions: number;
  };
  watchedSegmentIds: string[];
  createdAt: number;
  updatedAt: number;
  schemaVersion: number;
};

export type NoteRow = BaseEntity & {
  type:
    | 'concise'
    | 'detailed'
    | 'interview'
    | 'revision'
    | 'implementation'
    | 'contest'
    | 'custom';
  title: string;
  content: string;
  format: 'markdown' | 'plain';
  tags: string[];
  isPinned: boolean;
  playlistId?: string;
  timestampAnchors?: Array<{ startTime: number; endTime?: number; label?: string }>;
};

export type ChapterRow = BaseEntity & {
  title: string;
  chapters: Array<{
    id: string;
    title: string;
    startTime: number;
    endTime: number;
    summary: string;
    keyPoints: string[];
  }>;
};

export type FlashcardRow = BaseEntity & {
  flashcardId: string;
  playlistId?: string;
  front: string;
  back: string;
  difficulty: 'easy' | 'medium' | 'hard';
  nextReviewDate: number;
  intervalDays: number;
  repetitions: number;
  easeFactor: number;
  lastReviewedAt?: number;
};

export type QuizRow = BaseEntity & {
  quizId: string;
  mode: 'beginner' | 'interview' | 'revision';
  title: string;
  questions: Array<{
    id: string;
    question: string;
    options: string[];
    correctAnswerIndex: number;
    explanation: string;
    difficulty: 'easy' | 'medium' | 'hard';
    timestamp?: number;
  }>;
};

export type AnalyticsRow = BaseEntity & {
  kind: 'learning_event' | 'confusion' | 'ai_generation';
  payload: Record<string, unknown>;
};

export class StudyflowDB extends Dexie {
  transcripts!: Table<TranscriptRow, string>;
  semanticChunks!: Table<SemanticChunkRow, string>;
  embeddings!: Table<EmbeddingRow, string>;
  playlists!: Table<PlaylistRow, string>;
  studyPlans!: Table<StudyPlanRow, string>;
  notes!: Table<NoteRow, string>;
  chapters!: Table<ChapterRow, string>;
  flashcards!: Table<FlashcardRow, string>;
  quizzes!: Table<QuizRow, string>;
  analytics!: Table<AnalyticsRow, string>;

  constructor() {
    super('yt-studyflow');

    this.version(1).stores({
      transcripts: 'id, videoId, updatedAt',
      semanticChunks: 'id, videoId, startTime, endTime, updatedAt',
      embeddings: 'id, videoId, semanticChunkId, model, updatedAt',
      notes: 'id, videoId, type, createdAt, updatedAt, isPinned',
      chapters: 'id, videoId, updatedAt',
      flashcards: 'id, videoId, nextReviewDate, difficulty',
      quizzes: 'id, videoId, mode, updatedAt',
      analytics: 'id, videoId, kind, createdAt',
    });

    this.version(2).stores({
      transcripts: 'id, videoId, updatedAt',
      semanticChunks: 'id, videoId, playlistId, startTime, endTime, updatedAt',
      embeddings: 'id, videoId, semanticChunkId, model, updatedAt',
      playlists: 'id, updatedAt',
      studyPlans: 'id, playlistId, updatedAt',
      notes: 'id, videoId, playlistId, type, createdAt, updatedAt, isPinned',
      chapters: 'id, videoId, updatedAt',
      flashcards: 'id, videoId, playlistId, nextReviewDate, difficulty',
      quizzes: 'id, videoId, mode, updatedAt',
      analytics: 'id, videoId, kind, createdAt',
    });
  }
}

let dbInstance: StudyflowDB | null = null;

export function getDb(): StudyflowDB {
  if (!dbInstance) dbInstance = new StudyflowDB();
  return dbInstance;
}

export async function ensureDbReady(): Promise<void> {
  await getDb().open();
}

export const DbIds = {
  transcript: (videoId: string) => `transcript|${videoId}`,
  semanticChunk: (videoId: string, chunkId: string) => `chunk|${videoId}|${chunkId}`,
  embedding: (videoId: string, chunkId: string, model: string) =>
    `embed|${videoId}|${chunkId}|${model}`,
  note: (videoId: string, noteId: string) => `note|${videoId}|${noteId}`,
  chapters: (videoId: string) => `chapters|${videoId}`,
  flashcard: (videoId: string, cardId: string) => `fc|${videoId}|${cardId}`,
  quiz: (videoId: string, quizId: string) => `quiz|${videoId}|${quizId}`,
  analytics: (videoId: string, id: string) => `analytics|${videoId}|${id}`,
  playlist: (playlistId: string) => `playlist|${playlistId}`,
  studyPlan: (playlistId: string, topicSlug: string) => `study|${playlistId}|${topicSlug}`,
};
