import type { TranscriptChunk } from '@/types/transcript';

import { parseYouTubeTranscript } from './transcript.parser';

import {

  buildTimedtextUrl,

  chooseCaptionTrack,

  getCaptionTracksFromPage,

  getPlayerResponse,

  type CaptionTrack,

} from './transcript.captions';

import {

  fetchCaptionText,

  fetchCaptionTextWithFormats,

  fetchFromCapturedCache,

  waitForCapturedCaptions,

} from './transcript.fetch';

import {

  fetchInnertubeTranscriptData,

  fetchTranscriptParamsViaNext,

} from './transcript.innertube';

import {

  extractFromDomWithPanelOpen,

  parseCaptionPayload,

  parseInnertubeTranscript,

} from './transcript.parsers';

import type { RawCue } from './transcript.parser.types';



type ExtractResult =

  | {

      status: 'success';

      chunks: TranscriptChunk[];

      enhancedChunks: ReturnType<typeof parseYouTubeTranscript>['enhancedChunks'];

      totalDuration: number;

      metadata: {

        videoId: string;

        language: string;

        isAutoGenerated: boolean;

        fetchedAt: number;

      };

    }

  | { status: 'not-available'; reason: string }

  | { status: 'error'; reason: string };



function successResult(

  videoId: string,

  cues: RawCue[],

  track: Pick<CaptionTrack, 'languageCode' | 'isAutoGenerated'> | null

): ExtractResult {

  const parsed = parseYouTubeTranscript(videoId, cues);

  return {

    status: 'success',

    chunks: parsed.chunks,

    enhancedChunks: parsed.enhancedChunks,

    totalDuration: parsed.totalDuration,

    metadata: {

      videoId,

      language: track?.languageCode ?? 'en',

      isAutoGenerated: track?.isAutoGenerated ?? false,

      fetchedAt: Date.now(),

    },

  };

}



async function fetchFromTrack(baseUrl: string): Promise<RawCue[] | null> {

  let result = await fetchFromCapturedCache(baseUrl);

  if (!result.ok) {

    result = await fetchCaptionTextWithFormats(baseUrl);

  }

  if (!result.ok || !result.text) {

    result = await waitForCapturedCaptions(baseUrl);

  }

  if (!result.ok || !result.text) return null;



  const cues = parseCaptionPayload(result.text, result.contentType);

  if (!cues?.length) {

    console.warn('[YT StudyFlow] caption data received but parse failed', {

      via: result.via,

      len: result.text.length,

      preview: result.text.slice(0, 120),

    });

  }

  return cues;

}



async function fetchFromTimedtext(videoId: string, lang: string): Promise<RawCue[] | null> {

  const url = buildTimedtextUrl(videoId, lang);

  const result = await fetchCaptionText(url);

  if (!result.ok || !result.text) return null;

  return parseCaptionPayload(result.text, result.contentType);

}



async function fetchFromInnertube(

  videoId: string,

  player: Record<string, unknown> | null

): Promise<RawCue[] | null> {

  const params = await fetchTranscriptParamsViaNext(videoId, player);

  if (!params) {

    console.log('[YT StudyFlow] no InnerTube transcript params found');

    return null;

  }



  const data = await fetchInnertubeTranscriptData(params);

  if (!data) {

    console.warn('[YT StudyFlow] InnerTube get_transcript returned empty');

    return null;

  }



  return parseInnertubeTranscript(data);

}



export async function fetchTranscriptChunks(videoId: string): Promise<ExtractResult> {

  if (!videoId) {

    return { status: 'error', reason: 'Missing video ID' };

  }

  // Turn on CC in the player so timedtext / XHR capture can succeed without manual toggling.
  const { triggerPlayerCaptions } = await import('./transcript.pageFetch');
  await triggerPlayerCaptions();
  await new Promise((r) => setTimeout(r, 600));

  const player = getPlayerResponse();

  const tracks = getCaptionTracksFromPage();

  const track = chooseCaptionTrack(tracks);



  console.log('[YT StudyFlow] transcript:', {

    videoId,

    trackCount: tracks.length,

    hasPlayer: !!player,

    hasTrack: !!track,

    trackLang: track?.languageCode,

  });



  try {

    const innertubeCues = await fetchFromInnertube(videoId, player);

    if (innertubeCues?.length) {

      console.log('[YT StudyFlow] transcript loaded via InnerTube', innertubeCues.length);

      return successResult(videoId, innertubeCues, track);

    }



    if (track?.baseUrl) {

      const cues = await fetchFromTrack(track.baseUrl);

      if (cues?.length) {

        console.log('[YT StudyFlow] transcript loaded via caption URL', cues.length);

        return successResult(videoId, cues, track);

      }

    }



    const langs = [

      track?.languageCode,

      'en',

      'en-US',

      'en-GB',

      ...tracks.map((t) => t.languageCode),

    ].filter((l, i, a): l is string => !!l && a.indexOf(l) === i);



    for (const lang of langs) {

      const cues = await fetchFromTimedtext(videoId, lang);

      if (cues?.length) {

        console.log('[YT StudyFlow] transcript loaded via timedtext', lang, cues.length);

        return successResult(videoId, cues, { languageCode: lang, isAutoGenerated: false });

      }

    }



    for (const t of tracks) {

      if (t.baseUrl === track?.baseUrl) continue;

      const cues = await fetchFromTrack(t.baseUrl);

      if (cues?.length) {

        console.log('[YT StudyFlow] transcript loaded via alt track', t.languageCode);

        return successResult(videoId, cues, t);

      }

    }



    const domCues = await extractFromDomWithPanelOpen();

    if (domCues.length) {

      console.log('[YT StudyFlow] transcript loaded via DOM panel', domCues.length);

      return successResult(videoId, domCues, track);

    }



    if (!tracks.length) {

      return {

        status: 'not-available',

        reason: 'No captions on this video. Enable CC on the YouTube player first.',

      };

    }



    return {

      status: 'not-available',

      reason:

        'Captions exist but could not be downloaded. Turn on CC (subtitles) on the player, then click Retry.',

    };

  } catch (err) {

    return {

      status: 'error',

      reason: err instanceof Error ? err.message : String(err),

    };

  }

}


