/**
 * Extract YouTube player response + caption tracks from the page.
 */

export type CaptionTrack = {
  baseUrl: string;
  languageCode: string;
  kind?: string;
  isAutoGenerated?: boolean;
};

function extractBalancedJson(
  source: string,
  startIndex: number,
  openChar: '{' | '['
): string | null {
  const closeChar = openChar === '{' ? '}' : ']';
  let depth = 0;
  let inString = false;
  let escaped = false;

  for (let i = startIndex; i < source.length; i++) {
    const ch = source[i];

    if (inString) {
      if (escaped) {
        escaped = false;
        continue;
      }
      if (ch === '\\') {
        escaped = true;
        continue;
      }
      if (ch === '"') inString = false;
      continue;
    }

    if (ch === '"') {
      inString = true;
      continue;
    }
    if (ch === openChar) depth++;
    if (ch === closeChar) {
      depth--;
      if (depth === 0) return source.slice(startIndex, i + 1);
    }
  }

  return null;
}

function parsePlayerResponseFromScripts(): Record<string, unknown> | null {
  const markers = [
    'ytInitialPlayerResponse = ',
    'var ytInitialPlayerResponse = ',
    'window["ytInitialPlayerResponse"] = ',
  ];

  for (const script of document.querySelectorAll('script')) {
    const text = script.textContent ?? '';
    for (const marker of markers) {
      const idx = text.indexOf(marker);
      if (idx === -1) continue;
      const objStart = text.indexOf('{', idx + marker.length);
      if (objStart === -1) continue;
      const json = extractBalancedJson(text, objStart, '{');
      if (!json) continue;
      try {
        return JSON.parse(json) as Record<string, unknown>;
      } catch {
        continue;
      }
    }
  }

  return null;
}

export function getPlayerResponse(): Record<string, unknown> | null {
  const w = window as Window & {
    ytInitialPlayerResponse?: Record<string, unknown>;
    __ytInitialPlayerResponse?: Record<string, unknown>;
  };

  if (w.ytInitialPlayerResponse && typeof w.ytInitialPlayerResponse === 'object') {
    return w.ytInitialPlayerResponse;
  }
  if (w.__ytInitialPlayerResponse && typeof w.__ytInitialPlayerResponse === 'object') {
    return w.__ytInitialPlayerResponse;
  }

  return parsePlayerResponseFromScripts();
}

export function getCaptionTracksFromPlayer(
  player: Record<string, unknown> | null
): CaptionTrack[] {
  if (!player) return [];

  const captions = player.captions as Record<string, unknown> | undefined;
  const tracklist = captions?.playerCaptionsTracklistRenderer as
    | Record<string, unknown>
    | undefined;
  const raw = tracklist?.captionTracks;

  if (!Array.isArray(raw)) return [];

  return raw
    .map((t): CaptionTrack | null => {
      const track = t as Record<string, unknown>;
      const baseUrl = String(track.baseUrl ?? track.url ?? '');
      if (!baseUrl) return null;
      return {
        baseUrl,
        languageCode: String(track.languageCode ?? track.language ?? 'en'),
        kind: track.kind != null ? String(track.kind) : undefined,
        isAutoGenerated:
          track.isAutoGenerated === true ||
          String(track.kind ?? '').toLowerCase() === 'asr',
      };
    })
    .filter((t): t is CaptionTrack => t !== null);
}

export function getCaptionTracksFromPage(): CaptionTrack[] {
  const player = getPlayerResponse();
  const tracks = getCaptionTracksFromPlayer(player);
  if (tracks.length) return tracks;

  for (const script of document.querySelectorAll('script')) {
    const text = script.textContent ?? '';
    if (!text.includes('captionTracks')) continue;

    const idx = text.indexOf('"captionTracks"');
    if (idx === -1) continue;
    const arrStart = text.indexOf('[', idx);
    if (arrStart === -1) continue;

    const json = extractBalancedJson(text, arrStart, '[');
    if (!json) continue;

    try {
      const parsed = JSON.parse(json) as Array<Record<string, unknown>>;
      const fromScript = parsed
        .map((track): CaptionTrack | null => {
          const baseUrl = String(track.baseUrl ?? track.url ?? '');
          if (!baseUrl) return null;
          return {
            baseUrl,
            languageCode: String(track.languageCode ?? 'en'),
            kind: track.kind != null ? String(track.kind) : undefined,
            isAutoGenerated:
              track.isAutoGenerated === true ||
              String(track.kind ?? '').toLowerCase() === 'asr',
          };
        })
        .filter((t): t is CaptionTrack => t !== null);
      if (fromScript.length) return fromScript;
    } catch {
      continue;
    }
  }

  return [];
}

export function chooseCaptionTrack(tracks: CaptionTrack[]): CaptionTrack | null {
  if (!tracks.length) return null;
  const manual = tracks.find((t) => t.kind?.toLowerCase() === 'standard');
  const english = tracks.find((t) => t.languageCode.startsWith('en'));
  const auto = tracks.find((t) => t.isAutoGenerated);
  return manual ?? english ?? auto ?? tracks[0] ?? null;
}

function findTranscriptParamsDeep(node: unknown, depth = 0): string | null {
  if (!node || typeof node !== 'object' || depth > 24) return null;

  if (Array.isArray(node)) {
    for (const item of node) {
      const found = findTranscriptParamsDeep(item, depth + 1);
      if (found) return found;
    }
    return null;
  }

  const obj = node as Record<string, unknown>;

  const endpoint = obj.getTranscriptEndpoint as Record<string, unknown> | undefined;
  if (endpoint && typeof endpoint.params === 'string' && endpoint.params.length > 0) {
    return endpoint.params;
  }

  if (typeof obj.params === 'string' && obj.params.length > 0) {
    const command = obj.command as Record<string, unknown> | undefined;
    if (command?.getTranscriptEndpoint) {
      return obj.params;
    }
  }

  for (const value of Object.values(obj)) {
    const found = findTranscriptParamsDeep(value, depth + 1);
    if (found) return found;
  }

  return null;
}

export function getTranscriptInnertubeParams(
  player: Record<string, unknown> | null
): string | null {
  if (player) {
    const fromPlayer = findTranscriptParamsDeep(player);
    if (fromPlayer) return fromPlayer;
  }

  const initialData = (window as { ytInitialData?: Record<string, unknown> }).ytInitialData;
  if (initialData) {
    const fromInitial = findTranscriptParamsDeep(initialData);
    if (fromInitial) return fromInitial;
  }

  return null;
}

export function getInnertubeContext(): Record<string, unknown> {
  const ytcfg = (window as { ytcfg?: { data_?: Record<string, unknown> } }).ytcfg?.data_;
  const ctx = ytcfg?.INNERTUBE_CONTEXT;
  if (ctx && typeof ctx === 'object') return ctx as Record<string, unknown>;

  return {
    client: {
      hl: 'en',
      gl: 'US',
      clientName: 'WEB',
      clientVersion:
        String(ytcfg?.INNERTUBE_CLIENT_VERSION ?? '') || '2.20250101.00.00',
    },
  };
}

export function decodeTrackUrl(raw: string): string {
  return raw
    .replace(/\\u([0-9a-fA-F]{4})/g, (_, hex) =>
      String.fromCharCode(parseInt(hex, 16))
    )
    .replace(/\\\//g, '/')
    .replace(/^"|"$/g, '');
}

export function normalizeCaptionUrl(baseUrl: string, fmt: 'json3' | 'vtt' | 'srv3' = 'json3'): string {
  try {
    const decoded = decodeTrackUrl(baseUrl);
    const url = new URL(decoded, window.location.href);
    url.searchParams.set('fmt', fmt);
    return url.toString();
  } catch {
    return baseUrl;
  }
}

export function buildTimedtextUrl(videoId: string, lang: string): string {
  const url = new URL('https://www.youtube.com/api/timedtext');
  url.searchParams.set('v', videoId);
  url.searchParams.set('lang', lang);
  url.searchParams.set('fmt', 'json3');
  return url.toString();
}
