import { useEffect, useMemo, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Search,
  Sparkles,
  SkipBack,
  SkipForward,
  LocateFixed,
  Captions,
  Languages,
  RefreshCw,
} from 'lucide-react';
import { clsx } from 'clsx';
import { twMerge } from 'tailwind-merge';

import type { EnhancedTranscriptChunk } from '@/types/transcript';
import { useTranscriptStore } from './transcript.store';
import { formatTime } from '@lib/youtube';

function highlightText(text: string, query: string): React.ReactNode {
  const q = query.trim();
  if (!q) return text;

  const parts = text.split(new RegExp(`(${q.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')})`, 'gi'));
  return parts.map((part, i) =>
    part.toLowerCase() === q.toLowerCase() ? (
      <mark key={i} className="rounded bg-amber-400/25 text-amber-50 px-0.5">
        {part}
      </mark>
    ) : (
      part
    )
  );
}

type DisplayBlock = {
  id: string;
  start: number;
  end: number;
  text: string;
  chunkIds: string[];
};

function groupChunksForDisplay(chunks: EnhancedTranscriptChunk[]): DisplayBlock[] {
  const blocks: DisplayBlock[] = [];
  let buffer: EnhancedTranscriptChunk[] = [];

  const flush = () => {
    if (!buffer.length) return;
    blocks.push({
      id: buffer[0]!.id,
      start: buffer[0]!.start,
      end: buffer[buffer.length - 1]!.end,
      text: buffer.map((c) => c.text).join(' '),
      chunkIds: buffer.map((c) => c.id),
    });
    buffer = [];
  };

  for (const chunk of chunks) {
    const prev = buffer[buffer.length - 1];
    const gap = prev ? chunk.start - prev.end : 0;
    const combinedLen = buffer.reduce((n, c) => n + c.text.length, 0) + chunk.text.length;

    if (buffer.length && (gap > 3 || combinedLen > 280 || buffer.length >= 4)) {
      flush();
    }
    buffer.push(chunk);
  }
  flush();
  return blocks;
}

function TranscriptBlock({
  block,
  isActive,
  searchQuery,
  onJump,
}: {
  block: DisplayBlock;
  isActive: boolean;
  searchQuery: string;
  onJump: (seconds: number) => void;
}) {
  return (
    <motion.div
      layout
      initial={false}
      id={`yt-studyflow-block-${block.id}`}
      className={twMerge(
        clsx(
          'group relative grid grid-cols-[4.5rem_1fr] gap-x-3 border-l-2 py-3 pl-3 pr-2 transition-colors',
          isActive
            ? 'border-l-indigo-400 bg-indigo-500/10'
            : 'border-l-transparent hover:border-l-white/15 hover:bg-white/[0.03]'
        )
      )}
    >
      <button
        type="button"
        onClick={() => onJump(block.start)}
        className={twMerge(
          clsx(
            'self-start rounded-md px-1.5 py-0.5 text-left font-mono text-[11px] tabular-nums transition-colors',
            isActive
              ? 'bg-indigo-500/25 font-medium text-indigo-100'
              : 'text-white/45 group-hover:text-indigo-200'
          )
        )}
      >
        {formatTime(block.start)}
      </button>

      <p
        className={twMerge(
          clsx(
            'text-[13px] leading-[1.65] tracking-[0.01em]',
            isActive ? 'text-white' : 'text-white/78 group-hover:text-white/92'
          )
        )}
      >
        {highlightText(block.text, searchQuery)}
      </p>
    </motion.div>
  );
}

function SkeletonRows() {
  return (
    <div className="divide-y divide-white/5">
      {Array.from({ length: 8 }).map((_, i) => (
        <div key={i} className="grid grid-cols-[4.5rem_1fr] gap-3 px-3 py-3 animate-shimmer">
          <div className="h-5 w-12 rounded bg-white/10" />
          <div className="space-y-2">
            <div className="h-3 w-full rounded bg-white/10" />
            <div className="h-3 w-5/6 rounded bg-white/10" />
          </div>
        </div>
      ))}
    </div>
  );
}

export function TranscriptPanel({
  onJumpToTime,
  onReload,
}: {
  onJumpToTime: (seconds: number) => void;
  onReload?: () => void;
}) {
  const {
    enhancedChunks,
    filteredChunks,
    loading,
    status,
    error,
    availability,
    activeChunkIndex,
    searchQuery,
    language,
    isAutoGenerated,
    setSearchQuery,
  } = useTranscriptStore();

  const listRef = useRef<HTMLDivElement>(null);
  const activeChunk = activeChunkIndex >= 0 ? enhancedChunks[activeChunkIndex] : null;

  const displayBlocks = useMemo(
    () => groupChunksForDisplay(filteredChunks),
    [filteredChunks]
  );

  useEffect(() => {
    if (!activeChunk || searchQuery.trim()) return;
    const block = displayBlocks.find((b) => b.chunkIds.includes(activeChunk.id));
    const el = listRef.current?.querySelector(
      `#yt-studyflow-block-${CSS.escape(block?.id ?? activeChunk.id)}`
    );
    const container = listRef.current;
    if (!el || !container) return;

    const cRect = container.getBoundingClientRect();
    const eRect = el.getBoundingClientRect();
    if (eRect.top < cRect.top + 72 || eRect.bottom > cRect.bottom - 48) {
      el.scrollIntoView({ behavior: 'smooth', block: 'center' });
    }
  }, [activeChunk?.id, searchQuery, displayBlocks]);

  const stats = useMemo(() => {
    if (!enhancedChunks.length) return 'Waiting for transcript';
    if (searchQuery.trim()) return `${filteredChunks.length} matches · ${displayBlocks.length} blocks`;
    return `${enhancedChunks.length} lines · ${displayBlocks.length} paragraphs`;
  }, [enhancedChunks.length, filteredChunks.length, displayBlocks.length, searchQuery]);

  const jumpPrev = () => {
    if (activeChunkIndex <= 0) return;
    onJumpToTime(enhancedChunks[activeChunkIndex - 1]?.start ?? 0);
  };

  const jumpNext = () => {
    if (activeChunkIndex < 0 || activeChunkIndex >= enhancedChunks.length - 1) return;
    onJumpToTime(enhancedChunks[activeChunkIndex + 1]?.start ?? 0);
  };

  const scrollToActive = () => {
    if (!activeChunk) return;
    const block = displayBlocks.find((b) => b.chunkIds.includes(activeChunk.id));
    listRef.current
      ?.querySelector(`#yt-studyflow-block-${CSS.escape(block?.id ?? activeChunk.id)}`)
      ?.scrollIntoView({ behavior: 'smooth', block: 'center' });
  };

  return (
    <div className="flex h-full min-h-0 flex-col">
      <div className="sticky top-0 z-10 border-b border-white/8 bg-surface/95 backdrop-blur-xl">
        <div className="px-4 py-3">
          <div className="flex items-center justify-between gap-3">
            <div className="min-w-0">
              <div className="flex items-center gap-2">
                <Captions className="h-4 w-4 shrink-0 text-indigo-300" />
                <h2 className="truncate text-sm font-semibold text-white">Transcript</h2>
              </div>
              <p className="mt-0.5 truncate text-[11px] text-white/45">{stats}</p>
              {language && status === 'success' && (
                <p className="mt-0.5 flex items-center gap-1 text-[10px] text-white/40">
                  <Languages className="h-3 w-3" />
                  {language.toUpperCase()}
                  {isAutoGenerated ? ' · auto' : ' · manual'}
                </p>
              )}
            </div>

            <div className="flex shrink-0 items-center gap-0.5 rounded-xl border border-white/8 bg-white/[0.03] p-0.5">
              <button type="button" onClick={() => onReload?.()} className="rounded-lg p-1.5 text-white/60 hover:bg-white/8 hover:text-white" title="Reload">
                <RefreshCw className="h-3.5 w-3.5" />
              </button>
              <button type="button" onClick={jumpPrev} disabled={activeChunkIndex <= 0} className="rounded-lg p-1.5 text-white/60 hover:bg-white/8 disabled:opacity-30" title="Previous">
                <SkipBack className="h-3.5 w-3.5" />
              </button>
              <button type="button" onClick={jumpNext} disabled={activeChunkIndex < 0 || activeChunkIndex >= enhancedChunks.length - 1} className="rounded-lg p-1.5 text-white/60 hover:bg-white/8 disabled:opacity-30" title="Next">
                <SkipForward className="h-3.5 w-3.5" />
              </button>
              <button type="button" onClick={scrollToActive} disabled={!activeChunk} className="rounded-lg p-1.5 text-white/60 hover:bg-white/8 disabled:opacity-30" title="Current">
                <LocateFixed className="h-3.5 w-3.5" />
              </button>
            </div>
          </div>

          <div className="relative mt-2.5">
            <Search className="pointer-events-none absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-white/35" />
            <input
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search…"
              className="w-full rounded-xl border border-white/10 bg-white/[0.04] py-2 pl-9 pr-3 text-sm text-white placeholder:text-white/30 focus:border-indigo-400/40 focus:outline-none focus:ring-1 focus:ring-indigo-400/25"
            />
          </div>
        </div>
      </div>

      <div ref={listRef} className="min-h-0 flex-1 overflow-y-auto">
        <AnimatePresence mode="wait">
          {loading && (
            <motion.div key="loading" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
              <SkeletonRows />
            </motion.div>
          )}

          {!loading && availability === 'no-transcript' && (
            <motion.div key="empty" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="p-4">
              <div className="rounded-2xl border border-white/10 bg-white/[0.04] p-5">
                <div className="flex items-center gap-2 text-white/90">
                  <Sparkles className="h-4 w-4 text-indigo-300" />
                  <p className="text-sm font-medium">No transcript available</p>
                </div>
                <p className="mt-2 text-sm leading-6 text-white/55">
                  {error?.message ?? 'Enable CC on the YouTube player, then retry.'}
                </p>
                {onReload && (
                  <button type="button" onClick={onReload} className="mt-3 rounded-xl bg-indigo-500/20 px-3 py-2 text-xs text-white hover:bg-indigo-500/30">
                    Retry
                  </button>
                )}
              </div>
            </motion.div>
          )}

          {!loading && status === 'error' && (
            <motion.div key="error" className="p-4">
              <div className="rounded-2xl border border-red-500/25 bg-red-500/8 p-5">
                <p className="text-sm font-medium text-red-100">Could not load transcript</p>
                <p className="mt-2 text-sm text-red-100/75">{error?.message}</p>
              </div>
            </motion.div>
          )}

          {!loading && enhancedChunks.length > 0 && (
            <motion.div key="list" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="divide-y divide-white/[0.04] px-1 py-1">
              {displayBlocks.map((block) => (
                <TranscriptBlock
                  key={block.id}
                  block={block}
                  isActive={!!activeChunk && block.chunkIds.includes(activeChunk.id)}
                  searchQuery={searchQuery}
                  onJump={onJumpToTime}
                />
              ))}

              {displayBlocks.length === 0 && (
                <div className="p-6 text-center text-sm text-white/50">
                  No matches for &ldquo;{searchQuery}&rdquo;
                </div>
              )}
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
