import { create } from 'zustand';
import type {
  EnhancedTranscriptChunk,
  TranscriptChunk,
  TranscriptError,
  TranscriptStatus,
} from '@/types/transcript';

export type TranscriptAvailability = 'available' | 'no-transcript' | 'unknown';

interface TranscriptState {
  currentVideoId: string | null;
  chunks: TranscriptChunk[];
  enhancedChunks: EnhancedTranscriptChunk[];
  filteredChunks: EnhancedTranscriptChunk[];
  status: TranscriptStatus;
  error: TranscriptError | null;
  availability: TranscriptAvailability;
  loading: boolean;
  language: string | null;
  isAutoGenerated: boolean;
  activeTime: number;
  activeChunkIndex: number;
  searchQuery: string;

  setVideoId: (videoId: string | null) => void;
  setSearchQuery: (query: string) => void;
  setTranscriptLoading: () => void;
  setTranscriptError: (error: TranscriptError) => void;
  setTranscriptNoAvailability: (reason?: string) => void;
  setTranscript: (payload: {
    videoId: string;
    chunks: TranscriptChunk[];
    enhancedChunks: EnhancedTranscriptChunk[];
    language: string;
    isAutoGenerated: boolean;
  }) => void;
  setActiveTime: (time: number, index: number) => void;
}

function filterChunks(
  chunks: EnhancedTranscriptChunk[],
  query: string
): EnhancedTranscriptChunk[] {
  const q = query.trim().toLowerCase();
  if (!q) return chunks;
  return chunks.filter((c) => c.text.toLowerCase().includes(q));
}

const emptyState = {
  chunks: [] as TranscriptChunk[],
  enhancedChunks: [] as EnhancedTranscriptChunk[],
  filteredChunks: [] as EnhancedTranscriptChunk[],
  status: 'idle' as TranscriptStatus,
  error: null as TranscriptError | null,
  availability: 'unknown' as TranscriptAvailability,
  loading: false,
  language: null as string | null,
  isAutoGenerated: false,
  activeTime: 0,
  activeChunkIndex: -1,
  searchQuery: '',
};

export const useTranscriptStore = create<TranscriptState>((set, get) => ({
  currentVideoId: null,
  ...emptyState,

  setVideoId: (videoId) => {
    set({ currentVideoId: videoId, ...emptyState });
  },

  setSearchQuery: (query) => {
    const { enhancedChunks } = get();
    set({
      searchQuery: query,
      filteredChunks: filterChunks(enhancedChunks, query),
    });
  },

  setTranscriptLoading: () => {
    set({
      ...emptyState,
      status: 'loading',
      loading: true,
      currentVideoId: get().currentVideoId,
    });
  },

  setTranscriptError: (error) => {
    set({
      ...emptyState,
      status: 'error',
      error,
      currentVideoId: get().currentVideoId,
    });
  },

  setTranscriptNoAvailability: (reason) => {
    set({
      ...emptyState,
      status: 'no-transcript',
      availability: 'no-transcript',
      error: {
        type: 'not-available',
        message: reason ?? 'Transcript unavailable for this video',
      },
      currentVideoId: get().currentVideoId,
    });
  },

  setTranscript: ({ videoId, chunks, enhancedChunks, language, isAutoGenerated }) => {
    const q = get().searchQuery;
    set({
      currentVideoId: videoId,
      status: 'success',
      error: null,
      availability: 'available',
      loading: false,
      chunks,
      enhancedChunks,
      filteredChunks: filterChunks(enhancedChunks, q),
      language,
      isAutoGenerated,
      activeTime: 0,
      activeChunkIndex: -1,
    });
  },

  setActiveTime: (time, index) => {
    set((state) => {
      const timeChanged = Math.abs(state.activeTime - time) > 0.25;
      const indexChanged = state.activeChunkIndex !== index;
      if (!timeChanged && !indexChanged) return state;
      return { ...state, activeTime: time, activeChunkIndex: index };
    });
  },
}));
