import { useCallback, useEffect, useRef } from 'react';
import { fetchTranscriptChunks } from '@/features/transcript/transcript.service';
import { findActiveChunkIndex } from '@/features/transcript/transcript.parser';
import { useTranscriptStore } from '@/features/transcript/transcript.store';
import { STUDYFLOW_EVENTS } from '@lib/constants';

export function useTranscript(videoId: string) {
  const requestRef = useRef(0);
  const retryTimers = useRef<ReturnType<typeof setTimeout>[]>([]);

  const {
    setVideoId,
    setTranscriptLoading,
    setTranscript,
    setTranscriptError,
    setTranscriptNoAvailability,
    setActiveTime,
    status,
  } = useTranscriptStore();

  useEffect(() => {
    setVideoId(videoId);
  }, [videoId, setVideoId]);

  const loadTranscript = useCallback(async () => {
    if (!videoId) return;

    const current = useTranscriptStore.getState();
    if (current.status === 'success' && current.currentVideoId === videoId && current.chunks.length) {
      return;
    }

    const requestId = ++requestRef.current;
    if (current.status !== 'loading') {
      setTranscriptLoading();
    }

    const result = await fetchTranscriptChunks(videoId);
    if (requestId !== requestRef.current) return;

    if (result.status === 'success') {
      setTranscript({
        videoId,
        chunks: result.chunks,
        enhancedChunks: result.enhancedChunks,
        language: result.metadata.language,
        isAutoGenerated: result.metadata.isAutoGenerated,
      });
    } else if (result.status === 'not-available') {
      const again = useTranscriptStore.getState();
      if (again.status === 'success' && again.chunks.length) return;
      setTranscriptNoAvailability(result.reason);
      return;
    } else {
      const again = useTranscriptStore.getState();
      if (again.status === 'success' && again.chunks.length) return;
      setTranscriptError({ type: 'unknown', message: result.reason });
      return;
    }

    try {
      const { DbIds, ensureDbReady, getDb, nowMs } = await import('@lib/db');
      await ensureDbReady();
      const ts = nowMs();
      await getDb().transcripts.put({
        id: DbIds.transcript(videoId),
        videoId,
        language: result.metadata.language,
        isAutoGenerated: result.metadata.isAutoGenerated,
        metadata: {
          totalDuration: result.totalDuration,
          chunkCount: result.enhancedChunks.length,
          fetchedAt: result.metadata.fetchedAt,
        },
        chunks: result.enhancedChunks.map((c) => ({
          id: c.id,
          text: c.text,
          startTime: c.start,
          endTime: c.end,
          duration: c.duration,
          index: c.index,
        })),
        createdAt: ts,
        updatedAt: ts,
        schemaVersion: 1,
      });
    } catch {
      // non-fatal
    }
  }, [
    videoId,
    setTranscript,
    setTranscriptError,
    setTranscriptLoading,
    setTranscriptNoAvailability,
  ]);

  useEffect(() => {
    retryTimers.current.forEach(clearTimeout);
    retryTimers.current = [];

    void loadTranscript();

    // Player/captions may load after sidebar — retry with backoff (skip if already success)
    for (const delay of [2000, 5000, 10000]) {
      retryTimers.current.push(
        setTimeout(() => {
          const s = useTranscriptStore.getState();
          if (s.status === 'success' && s.chunks.length) return;
          void loadTranscript();
        }, delay)
      );
    }

    return () => {
      retryTimers.current.forEach(clearTimeout);
    };
  }, [videoId, loadTranscript]);

  useEffect(() => {
    const onTime = (e: Event) => {
      const detail = (e as CustomEvent<{ currentTime: number; videoId: string }>).detail;
      if (!detail || detail.videoId !== videoId) return;

      const chunks = useTranscriptStore.getState().enhancedChunks;
      const index = findActiveChunkIndex(chunks, detail.currentTime);
      setActiveTime(detail.currentTime, index);
    };

    window.addEventListener(STUDYFLOW_EVENTS.TIME_UPDATE, onTime);
    return () => window.removeEventListener(STUDYFLOW_EVENTS.TIME_UPDATE, onTime);
  }, [videoId, setActiveTime]);

  return { loadTranscript, status };
}
