/**
 * Transcript type definitions
 */

export type TranscriptChunk = {
  text: string;
  start: number;
  duration: number;
};

export interface EnhancedTranscriptChunk extends TranscriptChunk {
  id: string;
  end: number;
  index: number;
}

export interface TranscriptMetadata {
  videoId: string;
  language: string;
  isAutoGenerated: boolean;
  fetchedAt: number;
  totalDuration: number;
  chunkCount: number;
}

export type TranscriptStatus =
  | 'idle'
  | 'loading'
  | 'success'
  | 'error'
  | 'no-transcript';

export interface TranscriptError {
  type: 'network' | 'parsing' | 'not-available' | 'unknown';
  message: string;
}
